<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <WorkflowRepositoryConsumer>true</WorkflowRepositoryConsumer>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.21.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Core" Version="1.19.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.1" />
    <ProjectReference Include="..\..\src\Microsoft.Azure.Workflows.Sdk.csproj" />
    <WorkflowExpressionSchema Include="destinations.schema.json" />
  </ItemGroup>
  <Target Name="SetCodefulWorkerLanguage" AfterTargets="Build">
    <PropertyGroup>
      <CodefulWorkerConfig>$(OutputPath)worker.config.json</CodefulWorkerConfig>
    </PropertyGroup>
    <WriteLinesToFile File="$(CodefulWorkerConfig)"
                      Lines="$([System.IO.File]::ReadAllText('$(CodefulWorkerConfig)').Replace('dotnet-isolated','dotnet'))"
                      Overwrite="true" Condition="Exists('$(CodefulWorkerConfig)')" />
  </Target>
</Project>
