// <auto-generated/>

namespace TestNamespace
{
    using harness;
    using Microsoft.Azure.Workflows.Sdk;
    using Microsoft.Azure.Workflows.Sdk.Connectors;

    using Microsoft.Azure.Workflows.Sdk.Connectors.Msnweather;

    /// <summary>
    /// Main Class.
    /// </summary>
    public class Program
    {
        /// <summary>
        /// Main Class.
        /// </summary>
        public static void Main()
        {
            //RecruitmentWorkflow.AddRecruitmentWorkflow();

            //HttpWorkflow.AddHttpRequestResponseWorkflow();

            NestedWorkflow.AddNestedWorkflow();

            //RecurrenceWorkflow.AddRecurrenceWorkflow();

            //CreateTriggeredWorkflowTest();

            // WeatherWorkflow.AddWeatherWorkflow();

            WorkflowBuilderFactory.CreateWorkflows();
        }

        static void CreateTriggeredWorkflowTest()
        {
            var trigger = WorkflowTriggers.Managed.Msnweather("msnweather").WhenOnCurrentWeatherChange(
                () => "Seattle",
                () => OnCurrentWeatherChangeMeasureInput.Temperature,
                () => OnCurrentWeatherChangeWhenInput.IsEqualTo,
                () => 75d,
                () => "I"
            );
            trigger.WithName("woohoo");
            var builder = WorkflowBuilderFactory.CreateStatefulWorkflow("MyTriggeredWorkflow", trigger);
            builder.AddAction(WorkflowActions.BuiltIn.Compose(inputs: () => $"The trigger output {builder.TriggerOutput}"));
        }

        static void CreateWorkflow<T1, T2>(Action<T1, T2> x)
        {

        }

        static void CreateWorkflow2(Delegate x)
        {

        }
    }
}
