// -----------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
// -----------------------------------------------------------

namespace Microsoft.Azure.Workflows.Sdk
{
    /// <summary>
    /// Represents a named workflow operation in the workflow execution graph. This is the base interface
    /// for both actions (<see cref="IWorkflowAction"/>) and triggers (<see cref="IWorkflowTrigger"/>),
    /// providing the operation's identity and its connections to downstream child actions.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Each operation has a unique <see cref="Name"/> within a workflow that identifies it in the
    /// generated workflow definition. Names are auto-generated by default but can be overridden
    /// using the <c>.WithName()</c> extension method.
    /// </para>
    /// <para>
    /// The <see cref="Children"/> collection is populated automatically when <c>.Then()</c> is called
    /// on this operation, building the directed graph that represents the workflow's execution order.
    /// </para>
    /// </remarks>
    /// <seealso cref="IWorkflowAction"/>
    /// <seealso cref="IWorkflowTrigger"/>
    /// <seealso cref="WorkflowOperationExtensions.WithName{T}"/>
    public interface IWorkflowOperation : IChainableNode
    {
        /// <summary>
        /// Gets or sets the unique name of this operation within the workflow.
        /// This name is used as the key in the generated workflow definition and must be unique
        /// across all operations in the same workflow.
        /// </summary>
        string Name { get; set; }

        /// <summary>
        /// Gets the collection of child action nodes that are configured to run after this operation.
        /// This collection is populated automatically by <c>.Then()</c> calls and represents the
        /// outgoing edges of this node in the workflow graph.
        /// </summary>
        List<IWorkflowAction> Children { get; }
    }
}
