<Project>
  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)..\src\Utils\CSharpExpressionConverter.cs" Link="LegacyExpressionSources\Utils\CSharpExpressionConverter.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)..\src\Utils\ExpressionConverter.cs" Link="LegacyExpressionSources\Utils\ExpressionConverter.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)..\src\Expressions\CapturedValueResolver.cs" Link="LegacyExpressionSources\Expressions\CapturedValueResolver.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)..\src\Expressions\ComplexObjectConverter.cs" Link="LegacyExpressionSources\Expressions\ComplexObjectConverter.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)..\src\Expressions\CSharpExpressionConverter.cs" Link="LegacyExpressionSources\Expressions\CSharpExpressionConverter.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)..\src\Expressions\ExpressionExtensions.cs" Link="LegacyExpressionSources\Expressions\ExpressionExtensions.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)..\src\Expressions\ExpressionRenderer.cs" Link="LegacyExpressionSources\Expressions\ExpressionRenderer.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)..\src\Expressions\ExpressionVisitor.cs" Link="LegacyExpressionSources\Expressions\ExpressionVisitor.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)..\src\Expressions\LogicExpression.cs" Link="LegacyExpressionSources\Expressions\LogicExpression.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)..\src\Expressions\LogicExpressionConverter.cs" Link="LegacyExpressionSources\Expressions\LogicExpressionConverter.cs" />
  </ItemGroup>
</Project>
