// <auto-generated />

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Azure.Workflows.Sdk;

public class ApiConnectionActionInput(string path, string method, string connectionId) : RetryableActionInput
{
    #region IApiConnectionActionInput implementation

    /// <summary>
    /// Gets or sets the method of the request.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public string Method { get; set; } = method;

    /// <summary>
    /// Gets or sets the body of the request.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public object Body { get; set; }

    /// <summary>
    /// Gets or sets the queries for the request.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public Dictionary<string, string> Queries { get; set; } = new();

    public bool ShouldSerializeQueries() => Queries != null && Queries.Count > 0;

    /// <summary>
    /// Gets or sets the headers for the request.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public Dictionary<string, string> Headers { get; set; } = new();

    public bool ShouldSerializeHeaders() => Headers != null && Headers.Count > 0;

    #endregion

    /// <summary>
    /// Gets or sets the path for the request.
    /// </summary>
    [JsonProperty(Required = Required.Always)]
    public string Path { get; set; } = path;

    /// <summary>
    /// Gets or sets the host.
    /// </summary>
    [JsonProperty(Required = Required.Always)]
    public ApiConnectionHost Host { get; set; } = new ApiConnectionHost { Connection = new ApiConnection { ReferenceName = connectionId } };
}

/// <summary>
/// The type of the access key.
/// </summary>
public enum AccessKeyType
{
    /// <summary>
    /// The access key type is not specified.
    /// </summary>
    NotSpecified,

    /// <summary>
    /// The primary access key.
    /// </summary>
    Primary,

    /// <summary>
    /// The secondary access key.
    /// </summary>
    Secondary,
}

public abstract class ApiConnectionOperationInput(string connectionId)
{
    
    /// <summary>
    /// Gets or sets the host.
    /// </summary>
    [JsonProperty(Required = Required.Always)]
    public ApiConnectionHost Host { get; set; } = new ApiConnectionHost { Connection = new ApiConnection { ReferenceName = connectionId } };

}

/// <summary>
/// The ApiConnectionNotificationActionInput operation input.
/// </summary
/// >
public class ApiConnectionNotificationActionInput(string connectionId) : ApiConnectionOperationInput(connectionId)
{
    /// <summary>
    /// Gets or sets the subscribe parameters.
    /// </summary>
    [JsonProperty(Required = Required.Always)]
    public ApiConnectionNotificationWebhookActionInput Subscribe { get; set; }

    /// <summary>
    /// Gets or sets the fetch parameters.
    /// </summary>
    [JsonProperty(Required = Required.Always)]
    public ApiConnectionNotificationRecurrenceActionInput Fetch { get; set; }
}

/// <summary>
/// The Api Connection Notification Recurrence operation input.
/// </summary>
public class ApiConnectionNotificationRecurrenceActionInput 
{
    #region IApiConnectionActionInput implementation

    /// <summary>
    /// Gets or sets the method of the request.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public string Method { get; set; }

    /// <summary>
    /// Gets or sets the queries for the request.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public Dictionary<string, string> Queries { get; set; }

    /// <summary>
    /// Gets or sets the body of the request.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public JToken Body { get; set; }

    /// <summary>
    /// Gets or sets the headers for the request.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public Dictionary<string, string> Headers { get; set; }

    #endregion

    /// <summary>
    /// Gets or sets the path template for the request.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public PathTemplate PathTemplate { get; set; }
}

/// <summary>
/// The ApiConnectionNotification Webhook Action operation input.
/// </summary>
public class ApiConnectionNotificationWebhookActionInput
{
    #region IApiConnectionActionInput implementation

    /// <summary>
    /// Gets or sets the method of the request.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public string Method { get; set; }

    /// <summary>
    /// Gets or sets the queries for the request.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public Dictionary<string, string> Queries { get; set; }

    /// <summary>
    /// Gets or sets the body of the request.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public JToken Body { get; set; }

    /// <summary>
    /// Gets or sets the headers for the request.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public Dictionary<string, string> Headers { get; set; }

    #endregion

    /// <summary>
    /// Gets or sets the path template for the request.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public PathTemplate PathTemplate { get; set; }

    /// <summary>
    /// Gets or sets the access key type.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public AccessKeyType? AccessKeyType { get; set; }
}

/// <summary>
/// The path template.
/// </summary>
public class PathTemplate
{
    /// <summary>
    /// Gets or sets the template.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public string Template { get; set; }

    /// <summary>
    /// Gets or sets the parameters.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public Dictionary<string, string> Parameters { get; set; }
}

/// <summary>
/// The ApiConnectionWebhook operation input.
/// </summary>
public class ApiConnectionWebhookActionInput(string path, string method, string connectionId) : ApiConnectionActionInput(path, method, connectionId)
{
    #region Constant

    /// <summary>
    /// The path suffix for subscribe request.
    /// </summary>
    internal const string SubscribeUriPathSuffix = "$subscriptions";

    #endregion

    /// <summary>
    /// Gets or sets the schema of ApiConnectionWebhook operation.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public JToken Schema { get; set; }

    /// <summary>
    /// Gets or sets the access key type.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public AccessKeyType? AccessKeyType { get; set; }
}

public class ApiConnectionTriggerInput : ApiConnectionActionInput
{
    public ApiConnectionTriggerInput(string path, string method, string connectionId, FlowRecurrence recurrence, bool enableSplitOn)
        : base(path, method, connectionId)
    {
        this.Recurrence = recurrence.ToJToken();
        this.SplitOn = enableSplitOn ? "#{triggerOutputs()?[\"body\"]}" : null;
    }

    /// <summary>
    /// Gets or sets the recurrence of the flow template trigger.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1721:Property names", Justification = "By design.")]
    public JToken Recurrence { get; set; }

    /// <summary>
    /// Gets or sets the trigger split on.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public string SplitOn { get; set; }
}

public class ConnectorOperationAttribute : Attribute
{
    public string ConnectorName { get; set; } 
    public ConnectorType Type { get; set;  }
}

public class ConnectionNameAttribute : Attribute
{
}

public class DynamicValuesAttribute : Attribute
{
    public DynamicValuesAttribute(string operationId) { } 
}

public class ApiConnectionHost
{
    /// <summary>
    /// Gets or sets the API connection provider.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public ApiConnectionProvider Api { get; set; }

    /// <summary>
    /// Gets or sets the API connection.
    /// </summary>
    [JsonProperty(Required = Required.Always)]
    public ApiConnection Connection { get; set; }
}

public class ApiConnectionProvider
{
    /// <summary>
    /// Gets or sets the API connection provider runtime Url.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public Uri RuntimeUrl { get; set; }
}

public class ApiConnection
{
    /// <summary>
    /// Gets or sets the API connection name.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public string Name { get; set; }

    /// <summary>
    /// Gets or sets the API connection reference name.
    /// </summary>
    [JsonProperty(Required = Required.Default)]
    public string ReferenceName { get; set; }
}

/// <summary>
/// Response type back to Durable extension.
/// </summary>
internal class CodefulConnectorOperationResult
{
    /// <summary>
    /// Gets or sets the body of HTTP response received from the API.
    /// </summary>
    public string Content { get; set; }

    /// <summary>
    /// Gets or sets the HTTP Response message received from the API.
    /// </summary>
    public int StatusCode { get; set; }
}

public class ServiceProviderOperationInput
{
    public ServiceProviderConfiguration ServiceProviderConfiguration { get; set; }
    public object Parameters { get; set; }
}

public class ServiceProviderConfiguration
{
    public ServiceProviderConfiguration(
        string serviceProviderId,
        string operationId,
        string connectionName)
    {
        this.ServiceProviderId = serviceProviderId;
        this.OperationId = operationId;
        this.ConnectionName = connectionName;
    }

    /// <summary>
    /// Gets the connection name.
    /// </summary>
    [JsonProperty(Required = Required.Always)]
    public string ConnectionName { get; }

    /// <summary>
    /// Gets the operation id.
    /// </summary>
    [JsonProperty(Required = Required.Always)]
    public string OperationId { get; }

    /// <summary>
    /// Gets the service id.
    /// </summary>
    [JsonProperty(Required = Required.Always)]
    public string ServiceProviderId { get; }
}

[AttributeUsage(AttributeTargets.Method)]
internal class ConnectorOperatorInfoAttribute(string connectorName, string displayName, ConnectorType type) : Attribute
{
    public string ConnectorName { get; } = connectorName;
    public ConnectorType Type { get; } = type;

    public string DisplayName { get; } = displayName;
}

public enum ConnectorType
{
    Unspecified = 0,
    ApiManagement,
    ServiceProvider,
    AgentConnection
}
