<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <NoWarn>$(NoWarn);CS1591;CA2007;CS9113</NoWarn>
    <OutputType>Library</OutputType>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Authors>Microsoft Corporation</Authors>
    <Description>Microsoft Azure Logic Apps SDK</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Microsoft.Azure.Workflows.Sdk.Generators\**\*.cs" />
    <ProjectReference Include="Microsoft.Azure.Workflows.Sdk.Generators\Microsoft.Azure.Workflows.Sdk.Generators.csproj"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all" />
    <None Include="buildTransitive\Microsoft.Azure.Workflows.Sdk.props"
          Pack="true"
          PackagePath="buildTransitive\Microsoft.Azure.Workflows.Sdk.props" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Rpc" Version="1.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
      <ExcludeFromStyleCop Include="**\*.cs" />
  </ItemGroup>

  <Target Name="AddWorkflowExpressionGeneratorToPackage"
          BeforeTargets="_GetPackageFiles">
    <ItemGroup>
      <None Include="$(TargetDir)..\..\Microsoft.Azure.Workflows.Sdk.Generators\$(Configuration)\Microsoft.Azure.Workflows.Sdk.Generators.dll"
            Pack="true"
            PackagePath="analyzers\dotnet\cs\Microsoft.Azure.Workflows.Sdk.Generators.dll"
            Visible="false" />
    </ItemGroup>
  </Target>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Microsoft.Azure.Workflows.Sdk.ExpressionTests, PublicKey=00240000048000009400000006020000002400005253413100040000010001002549e359674acd5c9973cb966c1af490eb6c45b74a87ce5406a4d48175c997cfa82e1d55214075fca0bfe8ada9e092c8544ddad07ab446a1147e59953a2318f2efeb6f2e988273d1da68db43748fcb0d7114aa8fdd1810bdd88a5b855aa3cb0a5c8893a178dd46c6645a5a820d7873894830391a153650b51f5880e4d05df9cc</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Microsoft.Azure.Workflows.Sdk.CSharpExpressionTests, PublicKey=00240000048000009400000006020000002400005253413100040000010001002549e359674acd5c9973cb966c1af490eb6c45b74a87ce5406a4d48175c997cfa82e1d55214075fca0bfe8ada9e092c8544ddad07ab446a1147e59953a2318f2efeb6f2e988273d1da68db43748fcb0d7114aa8fdd1810bdd88a5b855aa3cb0a5c8893a178dd46c6645a5a820d7873894830391a153650b51f5880e4d05df9cc</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.21.9" IncludeAssets="all" />
    <PackageReference Include="Grpc.Core.Api" Version="2.60.0" IncludeAssets="all" />
    <PackageReference Include="Grpc.Net.Client" Version="2.60.0" IncludeAssets="all" />
    <PackageReference Include="Grpc.Tools" Version="2.53.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Abstractions" Version="1.3.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Grpc\Protos\IJobSessionService.proto" GrpcServices="Client" />
  </ItemGroup>
  
</Project>
