<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WorkflowRepositoryConsumer>true</WorkflowRepositoryConsumer>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="CultureHook\**\*.cs" />
    <ProjectReference Include="..\..\src\Microsoft.Azure.Workflows.Sdk.csproj" />
  </ItemGroup>
</Project>
